version: '2'
services:
  membersrvc:
    image: hyperledger/fabric-membersrvc
    command: membersrvc

  vp0:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=http://172.17.0.1:2375
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc
    command: sh -c "sleep 5; peer node start --peer-chaincodedev"
